module.exports = {
  "aaa": "American Automobile Association, Inc.",
  "aarp": "AARP",
  "abarth": "Fiat Chrysler Automobiles N.V.",
  "abb": "ABB Ltd",
  "abbott": "Abbott Laboratories, Inc.",
  "abbvie": "AbbVie Inc.",
  "abc": "Disney Enterprises, Inc.",
  "able": "Able Inc.",
  "abogado": "Top Level Domain Holdings Limited",
  "abudhabi": "Abu Dhabi Systems and Information Centre",
  "ac": "Network Information Center (AC Domain Registry)\nc/o Cable and Wireless (Ascension Island)",
  "academy": "Binky Moon, LLC",
  "accenture": "Accenture plc",
  "accountant": "dot Accountant Limited",
  "accountants": "Binky Moon, LLC",
  "aco": "ACO Severin Ahlmann GmbH & Co. KG",
  "active": "Active Network, LLC",
  "actor": "United TLD Holdco Ltd.",
  "ad": "Andorra Telecom",
  "adac": "Allgemeiner Deutscher Automobil-Club e.V. (ADAC)",
  "ads": "Charleston Road Registry Inc.",
  "adult": "ICM Registry AD LLC",
  "ae": "Telecommunication Regulatory Authority (TRA)",
  "aeg": "Aktiebolaget Electrolux",
  "aero": "Societe Internationale de Telecommunications Aeronautique (SITA INC USA)",
  "aetna": "Aetna Life Insurance Company",
  "af": "Ministry of Communications and IT",
  "afamilycompany": "Johnson Shareholdings, Inc.",
  "afl": "Australian Football League",
  "africa": "ZA Central Registry NPC trading as Registry.Africa",
  "ag": "UHSA School of Medicine",
  "agakhan": "Fondation Aga Khan (Aga Khan Foundation)",
  "agency": "Binky Moon, LLC",
  "ai": "Government of Anguilla",
  "aig": "American International Group, Inc.",
  "aigo": "aigo Digital Technology Co,Ltd.",
  "airbus": "Airbus S.A.S.",
  "airforce": "United TLD Holdco Ltd.",
  "airtel": "Bharti Airtel Limited",
  "akdn": "Fondation Aga Khan (Aga Khan Foundation)",
  "al": "Electronic and Postal Communications Authority - AKEP",
  "alfaromeo": "Fiat Chrysler Automobiles N.V.",
  "alibaba": "Alibaba Group Holding Limited",
  "alipay": "Alibaba Group Holding Limited",
  "allfinanz": "Allfinanz Deutsche Vermögensberatung Aktiengesellschaft",
  "allstate": "Allstate Fire and Casualty Insurance Company",
  "ally": "Ally Financial Inc.",
  "alsace": "REGION GRAND EST",
  "alstom": "ALSTOM",
  "am": "\"Internet Society\" Non-governmental Organization",
  "americanexpress": "American Express Travel Related Services Company, Inc.",
  "americanfamily": "AmFam, Inc.",
  "amex": "American Express Travel Related Services Company, Inc.",
  "amfam": "AmFam, Inc.",
  "amica": "Amica Mutual Insurance Company",
  "amsterdam": "Gemeente Amsterdam",
  "an": "Retired",
  "analytics": "Campus IP LLC",
  "android": "Charleston Road Registry Inc.",
  "anquan": "QIHOO 360 TECHNOLOGY CO. LTD.",
  "anz": "Australia and New Zealand Banking Group Limited",
  "ao": "Faculdade de Engenharia da Universidade Agostinho Neto",
  "aol": "OATH Inc.",
  "apartments": "Binky Moon, LLC",
  "app": "Charleston Road Registry Inc.",
  "apple": "Apple Inc.",
  "aq": "Antarctica Network Information Centre Limited",
  "aquarelle": "Aquarelle.com",
  "ar": "Presidencia de la Nación – Secretaría Legal y Técnica",
  "arab": "League of Arab States",
  "aramco": "Aramco Services Company",
  "archi": "STARTING DOT LIMITED",
  "army": "United TLD Holdco Ltd.",
  "arpa": "Internet Architecture Board (IAB)",
  "art": "UK Creative Ideas Limited",
  "arte": "Association Relative à la Télévision Européenne G.E.I.E.",
  "as": "AS Domain Registry",
  "asda": "Wal-Mart Stores, Inc.",
  "asia": "DotAsia Organisation Ltd.",
  "associates": "Binky Moon, LLC",
  "at": "nic.at GmbH",
  "athleta": "The Gap, Inc.",
  "attorney": "United TLD Holdco, Ltd",
  "au": ".au Domain Administration (auDA)",
  "auction": "United TLD HoldCo, Ltd.",
  "audi": "AUDI Aktiengesellschaft",
  "audible": "Amazon Registry Services, Inc.",
  "audio": "Uniregistry, Corp.",
  "auspost": "Australian Postal Corporation",
  "author": "Amazon Registry Services, Inc.",
  "auto": "Cars Registry Limited",
  "autos": "DERAutos, LLC",
  "avianca": "Aerovias del Continente Americano S.A. Avianca",
  "aw": "SETAR",
  "aws": "Amazon Registry Services, Inc.",
  "ax": "Ålands landskapsregering",
  "axa": "AXA SA",
  "az": "IntraNS",
  "azure": "Microsoft Corporation",
  "ba": "Universtiy Telinformatic Centre (UTIC)",
  "baby": "Johnson & Johnson Services, Inc.",
  "baidu": "Baidu, Inc.",
  "banamex": "Citigroup Inc.",
  "bananarepublic": "The Gap, Inc.",
  "band": "United TLD Holdco, Ltd",
  "bank": "fTLD Registry Services, LLC",
  "bar": "Punto 2012 Sociedad Anonima Promotora de Inversion de Capital Variable",
  "barcelona": "Municipi de Barcelona",
  "barclaycard": "Barclays Bank PLC",
  "barclays": "Barclays Bank PLC",
  "barefoot": "Gallo Vineyards, Inc.",
  "bargains": "Binky Moon, LLC",
  "baseball": "MLB Advanced Media DH, LLC",
  "basketball": "Fédération Internationale de Basketball (FIBA)",
  "bauhaus": "Werkhaus GmbH",
  "bayern": "Bayern Connect GmbH",
  "bb": "Government of Barbados\nMinistry of Economic Affairs and Development\nTelecommunications Unit",
  "bbc": "British Broadcasting Corporation",
  "bbt": "BB&T Corporation",
  "bbva": "BANCO BILBAO VIZCAYA ARGENTARIA, S.A.",
  "bcg": "The Boston Consulting Group, Inc.",
  "bcn": "Municipi de Barcelona",
  "bd": "Posts and Telecommunications Division",
  "be": "DNS Belgium vzw/asbl",
  "beats": "Beats Electronics, LLC",
  "beauty": "L'Oréal",
  "beer": "Top Level Domain Holdings Limited",
  "bentley": "Bentley Motors Limited",
  "berlin": "dotBERLIN GmbH & Co. KG",
  "best": "BestTLD Pty Ltd",
  "bestbuy": "BBY Solutions, Inc.",
  "bet": "Afilias plc",
  "bf": "ARCE-AutoritÈ de RÈgulation des Communications Electroniques",
  "bg": "Register.BG",
  "bh": "Telecommunications Regulatory Authority (TRA)",
  "bharti": "Bharti Enterprises (Holding) Private Limited",
  "bi": "Centre National de l'Informatique",
  "bible": "American Bible Society",
  "bid": "dot Bid Limited",
  "bike": "Binky Moon, LLC",
  "bing": "Microsoft Corporation",
  "bingo": "Binky Moon, LLC",
  "bio": "STARTING DOT LIMITED",
  "biz": "Neustar, Inc.",
  "bj": "Benin Telecoms S.A.",
  "bl": "Not assigned",
  "black": "Afilias plc",
  "blackfriday": "Uniregistry, Corp.",
  "blanco": "BLANCO GmbH + Co KG",
  "blockbuster": "Dish DBS Corporation",
  "blog": "Knock Knock WHOIS There, LLC",
  "bloomberg": "Bloomberg IP Holdings LLC",
  "blue": "Afilias plc",
  "bm": "Registry General Department, Ministry of Home Affairs",
  "bms": "Bristol-Myers Squibb Company",
  "bmw": "Bayerische Motoren Werke Aktiengesellschaft",
  "bn": "Authority for Info-communications Technology Industry of Brunei Darussalam (AITI)",
  "bnl": "Banca Nazionale del Lavoro",
  "bnpparibas": "BNP Paribas",
  "bo": "Agencia para el Desarrollo de la Información de la Sociedad en Bolivia",
  "boats": "DERBoats, LLC",
  "boehringer": "Boehringer Ingelheim International GmbH",
  "bofa": "Bank of America Corporation",
  "bom": "Núcleo de Informação e Coordenação do Ponto BR - NIC.br",
  "bond": "Bond University Limited",
  "boo": "Charleston Road Registry Inc.",
  "book": "Amazon Registry Services, Inc.",
  "booking": "Booking.com B.V.",
  "boots": "Not assigned",
  "bosch": "Robert Bosch GMBH",
  "bostik": "Bostik SA",
  "boston": "Boston TLD Management, LLC",
  "bot": "Amazon Registry Services, Inc.",
  "boutique": "Binky Moon, LLC",
  "box": "NS1 Limited",
  "bq": "Not assigned",
  "br": "Comite Gestor da Internet no Brasil",
  "bradesco": "Banco Bradesco S.A.",
  "bridgestone": "Bridgestone Corporation",
  "broadway": "Celebrate Broadway, Inc.",
  "broker": "DOTBROKER REGISTRY LTD",
  "brother": "Brother Industries, Ltd.",
  "brussels": "DNS.be vzw",
  "bs": "The College of the Bahamas",
  "bt": "Ministry of Information and Communications",
  "budapest": "Top Level Domain Holdings Limited",
  "bugatti": "Bugatti International SA",
  "build": "Plan Bee LLC",
  "builders": "Binky Moon, LLC",
  "business": "Binky Moon, LLC",
  "buy": "Amazon Registry Services, INC",
  "buzz": "DOTSTRATEGY CO.",
  "bv": "UNINETT Norid A/S",
  "bw": "Botswana Communications Regulatory Authority (BOCRA)",
  "by": "Reliable Software, Ltd.",
  "bz": "University of Belize",
  "bzh": "Association www.bzh",
  "ca": "Canadian Internet Registration Authority (CIRA) Autorité Canadienne pour les enregistrements Internet (ACEI)",
  "cab": "Binky Moon, LLC",
  "cafe": "Binky Moon, LLC",
  "cal": "Charleston Road Registry Inc.",
  "call": "Amazon Registry Services, Inc.",
  "calvinklein": "PVH gTLD Holdings LLC",
  "cam": "AC Webconnecting Holding B.V.",
  "camera": "Binky Moon, LLC",
  "camp": "Binky Moon, LLC",
  "cancerresearch": "Australian Cancer Research Foundation",
  "canon": "Canon Inc.",
  "capetown": "ZA Central Registry NPC trading as ZA Central Registry",
  "capital": "Binky Moon, LLC",
  "capitalone": "Capital One Financial Corporation",
  "car": "Cars Registry Limited",
  "caravan": "Caravan International, Inc.",
  "cards": "Binky Moon, LLC",
  "care": "Binky Moon, LLC",
  "career": "dotCareer LLC",
  "careers": "Binky Moon, LLC",
  "cars": "Cars Registry Limited",
  "cartier": "Richemont DNS Inc.",
  "casa": "Top Level Domain Holdings Limited",
  "case": "CNH Industrial N.V.",
  "caseih": "CNH Industrial N.V.",
  "cash": "Binky Moon, LLC",
  "casino": "Binky Moon, LLC",
  "cat": "Fundacio puntCAT",
  "catering": "Binky Moon, LLC",
  "catholic": "Pontificium Consilium de Comunicationibus Socialibus (PCCS) (Pontifical Council for Social Communication)",
  "cba": "COMMONWEALTH BANK OF AUSTRALIA",
  "cbn": "The Christian Broadcasting Network, Inc.",
  "cbre": "CBRE, Inc.",
  "cbs": "CBS Domains Inc.",
  "cc": "eNIC Cocos (Keeling) Islands Pty.\nLtd. d/b/a Island Internet Services",
  "cd": "Office Congolais des Postes et Télécommunications - OCPT",
  "ceb": "The Corporate Executive Board Company",
  "center": "Binky Moon, LLC",
  "ceo": "CEOTLD Pty Ltd",
  "cern": "European Organization for Nuclear Research (\"CERN\")",
  "cf": "Societe Centrafricaine de Telecommunications (SOCATEL)",
  "cfa": "CFA Institute",
  "cfd": "DOTCFD REGISTRY LTD",
  "cg": "ONPT Congo and Interpoint Switzerland",
  "ch": "SWITCH The Swiss Education & Research Network",
  "chanel": "Chanel International B.V.",
  "channel": "Charleston Road Registry Inc.",
  "charity": "Corn Lake, LLC",
  "chase": "JPMorgan Chase Bank, National Association",
  "chat": "Binky Moon, LLC",
  "cheap": "Binky Moon, LLC",
  "chintai": "CHINTAI Corporation",
  "chloe": "Not assigned",
  "christmas": "Uniregistry, Corp.",
  "chrome": "Charleston Road Registry Inc.",
  "chrysler": "FCA US LLC.",
  "church": "Binky Moon, LLC",
  "ci": "Autorité de Régulation des Télécommunications/TIC de Côte d’lvoire (ARTCI)",
  "cipriani": "Hotel Cipriani Srl",
  "circle": "Amazon Registry Services, Inc.",
  "cisco": "Cisco Technology, Inc.",
  "citadel": "Citadel Domain LLC",
  "citi": "Citigroup Inc.",
  "citic": "CITIC Group Corporation",
  "city": "Binky Moon, LLC",
  "cityeats": "Lifestyle Domain Holdings, Inc.",
  "ck": "Telecom Cook Islands Ltd.",
  "cl": "NIC Chile (University of Chile)",
  "claims": "Binky Moon, LLC",
  "cleaning": "Binky Moon, LLC",
  "click": "Uniregistry, Corp.",
  "clinic": "Binky Moon, LLC",
  "clinique": "The Estée Lauder Companies Inc.",
  "clothing": "Binky Moon, LLC",
  "cloud": "ARUBA PEC S.p.A.",
  "club": ".CLUB DOMAINS, LLC",
  "clubmed": "Club Méditerranée S.A.",
  "cm": "Cameroon Telecommunications (CAMTEL)",
  "cn": "China Internet Network Information Center (CNNIC)",
  "co": ".CO Internet S.A.S.",
  "coach": "Binky Moon, LLC",
  "codes": "Binky Moon, LLC",
  "coffee": "Binky Moon, LLC",
  "college": "XYZ.COM LLC",
  "cologne": "punkt.wien GmbH",
  "com": "VeriSign Global Registry Services",
  "comcast": "Comcast IP Holdings I, LLC",
  "commbank": "COMMONWEALTH BANK OF AUSTRALIA",
  "community": "Binky Moon, LLC",
  "company": "Binky Moon, LLC",
  "compare": "iSelect Ltd",
  "computer": "Binky Moon, LLC",
  "comsec": "VeriSign, Inc.",
  "condos": "Binky Moon, LLC",
  "construction": "Binky Moon, LLC",
  "consulting": "United TLD Holdco, LTD.",
  "contact": "Top Level Spectrum, Inc.",
  "contractors": "Binky Moon, LLC",
  "cooking": "Top Level Domain Holdings Limited",
  "cookingchannel": "Lifestyle Domain Holdings, Inc.",
  "cool": "Binky Moon, LLC",
  "coop": "DotCooperation LLC",
  "corsica": "Collectivité Territoriale de Corse",
  "country": "Top Level Domain Holdings Limited",
  "coupon": "Amazon Registry Services, Inc.",
  "coupons": "Binky Moon, LLC",
  "courses": "OPEN UNIVERSITIES AUSTRALIA PTY LTD",
  "cr": "National Academy of Sciences\nAcademia Nacional de Ciencias",
  "credit": "Binky Moon, LLC",
  "creditcard": "Binky Moon, LLC",
  "creditunion": "CUNA Performance Resources, LLC",
  "cricket": "dot Cricket Limited",
  "crown": "Crown Equipment Corporation",
  "crs": "Federated Co-operatives Limited",
  "cruise": "Viking River Cruises (Bermuda) Ltd.",
  "cruises": "Binky Moon, LLC",
  "csc": "Alliance-One Services, Inc.",
  "cu": "CENIAInternet\nIndustria y San Jose\nCapitolio Nacional",
  "cuisinella": "SALM S.A.S.",
  "cv": "Agência Nacional das Comunicações (ANAC)",
  "cw": "University of Curacao",
  "cx": "Christmas Island Domain Administration Limited",
  "cy": "University of Cyprus",
  "cymru": "Nominet UK",
  "cyou": "Beijing Gamease Age Digital Technology Co., Ltd.",
  "cz": "CZ.NIC, z.s.p.o",
  "dabur": "Dabur India Limited",
  "dad": "Charleston Road Registry Inc.",
  "dance": "United TLD Holdco Ltd.",
  "data": "Dish DBS Corporation",
  "date": "dot Date Limited",
  "dating": "Binky Moon, LLC",
  "datsun": "NISSAN MOTOR CO., LTD.",
  "day": "Charleston Road Registry Inc.",
  "dclk": "Charleston Road Registry Inc.",
  "dds": "Minds + Machines Group Limited",
  "de": "DENIC eG",
  "deal": "Amazon Registry Services, Inc.",
  "dealer": "Dealer Dot Com, Inc.",
  "deals": "Binky Moon, LLC",
  "degree": "United TLD Holdco, Ltd",
  "delivery": "Binky Moon, LLC",
  "dell": "Dell Inc.",
  "deloitte": "Deloitte Touche Tohmatsu",
  "delta": "Delta Air Lines, Inc.",
  "democrat": "United TLD Holdco Ltd.",
  "dental": "Binky Moon, LLC",
  "dentist": "United TLD Holdco, Ltd",
  "desi": "Desi Networks LLC",
  "design": "Top Level Design, LLC",
  "dev": "Charleston Road Registry Inc.",
  "dhl": "Deutsche Post AG",
  "diamonds": "Binky Moon, LLC",
  "diet": "Uniregistry, Corp.",
  "digital": "Binky Moon, LLC",
  "direct": "Binky Moon, LLC",
  "directory": "Binky Moon, LLC",
  "discount": "Binky Moon, LLC",
  "discover": "Discover Financial Services",
  "dish": "Dish DBS Corporation",
  "diy": "Lifestyle Domain Holdings, Inc.",
  "dj": "Djibouti Telecom S.A",
  "dk": "Dansk Internet Forum",
  "dm": "DotDM Corporation",
  "dnp": "Dai Nippon Printing Co., Ltd.",
  "do": "Pontificia Universidad Catolica Madre y Maestra\nRecinto Santo Tomas de Aquino",
  "docs": "Charleston Road Registry Inc.",
  "doctor": "Binky Moon, LLC",
  "dodge": "FCA US LLC.",
  "dog": "Binky Moon, LLC",
  "doha": "Communications Regulatory Authority (CRA)",
  "domains": "Binky Moon, LLC",
  "doosan": "Retired",
  "dot": "Dish DBS Corporation",
  "download": "dot Support Limited",
  "drive": "Charleston Road Registry Inc.",
  "dtv": "Dish DBS Corporation",
  "dubai": "Dubai Smart Government Department",
  "duck": "Johnson Shareholdings, Inc.",
  "dunlop": "The Goodyear Tire & Rubber Company",
  "duns": "The Dun & Bradstreet Corporation",
  "dupont": "E. I. du Pont de Nemours and Company",
  "durban": "ZA Central Registry NPC trading as ZA Central Registry",
  "dvag": "Deutsche Vermögensberatung Aktiengesellschaft DVAG",
  "dvr": "Hughes Satellite Systems Corporation",
  "dz": "CERIST",
  "earth": "Interlink Co., Ltd.",
  "eat": "Charleston Road Registry Inc.",
  "ec": "ECUADORDOMAIN S.A.",
  "eco": "Big Room Inc.",
  "edeka": "EDEKA Verband kaufmännischer Genossenschaften e.V.",
  "edu": "EDUCAUSE",
  "education": "Binky Moon, LLC",
  "ee": "Eesti Interneti Sihtasutus (EIS)",
  "eg": "Egyptian Universities Network (EUN)\nSupreme Council of Universities",
  "eh": "Not assigned",
  "email": "Binky Moon, LLC",
  "emerck": "Merck KGaA",
  "energy": "Binky Moon, LLC",
  "engineer": "United TLD Holdco Ltd.",
  "engineering": "Binky Moon, LLC",
  "enterprises": "Binky Moon, LLC",
  "epost": "Deutsche Post AG",
  "epson": "Seiko Epson Corporation",
  "equipment": "Binky Moon, LLC",
  "er": "Eritrea Telecommunication Services Corporation (EriTel)",
  "ericsson": "Telefonaktiebolaget L M Ericsson",
  "erni": "ERNI Group Holding AG",
  "es": "Red.es",
  "esq": "Charleston Road Registry Inc.",
  "estate": "Binky Moon, LLC",
  "esurance": "Esurance Insurance Company",
  "et": "Ethio telecom",
  "etisalat": "Emirates Telecommunications Corporation (trading as Etisalat)",
  "eu": "EURid vzw/asbl",
  "eurovision": "European Broadcasting Union (EBU)",
  "eus": "Puntueus Fundazioa",
  "events": "Binky Moon, LLC",
  "everbank": "EverBank",
  "exchange": "Binky Moon, LLC",
  "expert": "Binky Moon, LLC",
  "exposed": "Binky Moon, LLC",
  "express": "Binky Moon, LLC",
  "extraspace": "Extra Space Storage LLC",
  "fage": "Fage International S.A.",
  "fail": "Binky Moon, LLC",
  "fairwinds": "FairWinds Partners, LLC",
  "faith": "dot Faith Limited",
  "family": "United TLD Holdco Ltd.",
  "fan": "Asiamix Digital Ltd",
  "fans": "Asiamix Digital Limited",
  "farm": "Binky Moon, LLC",
  "farmers": "Farmers Insurance Exchange",
  "fashion": "Top Level Domain Holdings Limited",
  "fast": "Amazon Registry Services, Inc.",
  "fedex": "Federal Express Corporation",
  "feedback": "Top Level Spectrum, Inc.",
  "ferrari": "Fiat Chrysler Automobiles N.V.",
  "ferrero": "Ferrero Trading Lux S.A.",
  "fi": "Finnish Communications Regulatory Authority",
  "fiat": "Fiat Chrysler Automobiles N.V.",
  "fidelity": "Fidelity Brokerage Services LLC",
  "fido": "Rogers Communications Canada Inc.",
  "film": "Motion Picture Domain Registry Pty Ltd",
  "final": "Núcleo de Informação e Coordenação do Ponto BR - NIC.br",
  "finance": "Binky Moon, LLC",
  "financial": "Binky Moon, LLC",
  "fire": "Amazon Registry Services, Inc.",
  "firestone": "Bridgestone Licensing Services, Inc.",
  "firmdale": "Firmdale Holdings Limited",
  "fish": "Binky Moon, LLC",
  "fishing": "Top Level Domain Holdings Limited",
  "fit": "Minds + Machines Group Limited",
  "fitness": "Binky Moon, LLC",
  "fj": "The University of the South Pacific\nIT Services",
  "fk": "Falkland Islands Government",
  "flickr": "Yahoo! Domain Services Inc.",
  "flights": "Binky Moon, LLC",
  "flir": "FLIR Systems, Inc.",
  "florist": "Binky Moon, LLC",
  "flowers": "Uniregistry, Corp.",
  "flsmidth": "Retired",
  "fly": "Charleston Road Registry Inc.",
  "fm": "FSM Telecommunications Corporation",
  "fo": "FO Council",
  "foo": "Charleston Road Registry Inc.",
  "food": "Lifestyle Domain Holdings, Inc.",
  "foodnetwork": "Lifestyle Domain Holdings, Inc.",
  "football": "Binky Moon, LLC",
  "ford": "Ford Motor Company",
  "forex": "DOTFOREX REGISTRY LTD",
  "forsale": "United TLD Holdco, LLC",
  "forum": "Fegistry, LLC",
  "foundation": "Binky Moon, LLC",
  "fox": "FOX Registry, LLC",
  "fr": "Association Française pour le Nommage Internet en Coopération (A.F.N.I.C.)",
  "free": "Amazon Registry Services, Inc.",
  "fresenius": "Fresenius Immobilien-Verwaltungs-GmbH",
  "frl": "FRLregistry B.V.",
  "frogans": "OP3FT",
  "frontdoor": "Lifestyle Domain Holdings, Inc.",
  "frontier": "Frontier Communications Corporation",
  "ftr": "Frontier Communications Corporation",
  "fujitsu": "Fujitsu Limited",
  "fujixerox": "Xerox DNHC LLC",
  "fun": "DotSpace, Inc.",
  "fund": "Binky Moon, LLC",
  "furniture": "Binky Moon, LLC",
  "futbol": "United TLD Holdco, Ltd.",
  "fyi": "Binky Moon, LLC",
  "ga": "Agence Nationale des Infrastructures Numériques et des Fréquences (ANINF)",
  "gal": "Asociación puntoGAL",
  "gallery": "Binky Moon, LLC",
  "gallo": "Gallo Vineyards, Inc.",
  "gallup": "Gallup, Inc.",
  "game": "Uniregistry, Corp.",
  "games": "United TLD Holdco Ltd.",
  "gap": "The Gap, Inc.",
  "garden": "Top Level Domain Holdings Limited",
  "gb": "Reserved Domain - IANA",
  "gbiz": "Charleston Road Registry Inc.",
  "gd": "The National Telecommunications Regulatory Commission (NTRC)",
  "gdn": "Joint Stock Company \"Navigation-information systems\"",
  "ge": "Caucasus Online LLC",
  "gea": "GEA Group Aktiengesellschaft",
  "gent": "Combell nv",
  "genting": "Resorts World Inc. Pte. Ltd.",
  "george": "Wal-Mart Stores, Inc.",
  "gf": "Net Plus",
  "gg": "Island Networks Ltd.",
  "ggee": "GMO Internet, Inc.",
  "gh": "Network Computer Systems Limited",
  "gi": "Sapphire Networks",
  "gift": "Uniregistry, Corp.",
  "gifts": "Binky Moon, LLC",
  "gives": "United TLD Holdco Ltd.",
  "giving": "Giving Limited",
  "gl": "TELE Greenland A/S",
  "glade": "Johnson Shareholdings, Inc.",
  "glass": "Binky Moon, LLC",
  "gle": "Charleston Road Registry Inc.",
  "global": "Dot Global Domain Registry Limited",
  "globo": "Globo Comunicação e Participações S.A",
  "gm": "GM-NIC",
  "gmail": "Charleston Road Registry Inc.",
  "gmbh": "Binky Moon, LLC",
  "gmo": "GMO Internet, Inc.",
  "gmx": "1&1 Mail & Media GmbH",
  "gn": "Centre National des Sciences Halieutiques de Boussoura",
  "godaddy": "Go Daddy East, LLC",
  "gold": "Binky Moon, LLC",
  "goldpoint": "YODOBASHI CAMERA CO.,LTD.",
  "golf": "Binky Moon, LLC",
  "goo": "NTT Resonant Inc.",
  "goodhands": "Allstate Fire and Casualty Insurance Company",
  "goodyear": "The Goodyear Tire & Rubber Company",
  "goog": "Charleston Road Registry Inc.",
  "google": "Charleston Road Registry Inc.",
  "gop": "Republican State Leadership Committee, Inc.",
  "got": "Amazon Registry Services, Inc.",
  "gov": "General Services Administration\nAttn: QTDC, 2E08 (.gov Domain Registration)",
  "gp": "Networking Technologies Group",
  "gq": "GETESA",
  "gr": "ICS-FORTH GR",
  "grainger": "Grainger Registry Services, LLC",
  "graphics": "Binky Moon, LLC",
  "gratis": "Binky Moon, LLC",
  "green": "DotGreen Registry Limited",
  "gripe": "Binky Moon, LLC",
  "grocery": "Wal-Mart Stores, Inc.",
  "group": "Binky Moon, LLC",
  "gs": "Government of South Georgia and South Sandwich Islands (GSGSSI)",
  "gt": "Universidad del Valle de Guatemala",
  "gu": "University of Guam",
  "guardian": "The Guardian Life Insurance Company of America",
  "gucci": "Guccio Gucci S.p.a.",
  "guge": "Charleston Road Registry Inc.",
  "guide": "Binky Moon, LLC",
  "guitars": "Uniregistry, Corp.",
  "guru": "Binky Moon, LLC",
  "gw": "Autoridade Reguladora Nacional - Tecnologias de Informação e Comunicação da Guiné-Bissau",
  "gy": "University of Guyana",
  "hair": "L'Oreal",
  "hamburg": "Hamburg Top-Level-Domain GmbH",
  "hangout": "Charleston Road Registry Inc.",
  "haus": "United TLD Holdco, LTD.",
  "hbo": "HBO Registry Services, Inc.",
  "hdfc": "HOUSING DEVELOPMENT FINANCE CORPORATION LIMITED",
  "hdfcbank": "HDFC Bank Limited",
  "health": "DotHealth, LLC",
  "healthcare": "Binky Moon, LLC",
  "help": "Uniregistry, Corp.",
  "helsinki": "City of Helsinki",
  "here": "Charleston Road Registry Inc.",
  "hermes": "Hermes International",
  "hgtv": "Lifestyle Domain Holdings, Inc.",
  "hiphop": "Uniregistry, Corp.",
  "hisamitsu": "Hisamitsu Pharmaceutical Co.,Inc.",
  "hitachi": "Hitachi, Ltd.",
  "hiv": "Uniregistry, Corp.",
  "hk": "Hong Kong Internet Registration Corporation Ltd.",
  "hkt": "PCCW-HKT DataCom Services Limited",
  "hm": "HM Domain Registry",
  "hn": "Red de Desarrollo Sostenible Honduras",
  "hockey": "Binky Moon, LLC",
  "holdings": "Binky Moon, LLC",
  "holiday": "Binky Moon, LLC",
  "homedepot": "Home Depot Product Authority, LLC",
  "homegoods": "The TJX Companies, Inc.",
  "homes": "DERHomes, LLC",
  "homesense": "The TJX Companies, Inc.",
  "honda": "Honda Motor Co., Ltd.",
  "honeywell": "Honeywell GTLD LLC",
  "horse": "Top Level Domain Holdings Limited",
  "hospital": "Binky Moon, LLC",
  "host": "DotHost Inc.",
  "hosting": "Uniregistry, Corp.",
  "hot": "Amazon Registry Services, Inc.",
  "hoteles": "Travel Reservations SRL",
  "hotels": "Booking.com B.V.",
  "hotmail": "Microsoft Corporation",
  "house": "Binky Moon, LLC",
  "how": "Charleston Road Registry Inc.",
  "hr": "CARNet - Croatian Academic and Research Network",
  "hsbc": "HSBC Global Services (UK) Limited",
  "ht": "Consortium FDS/RDDH",
  "htc": "Not assigned",
  "hu": "Council of Hungarian Internet Providers (CHIP)",
  "hughes": "Hughes Satellite Systems Corporation",
  "hyatt": "Hyatt GTLD, L.L.C.",
  "hyundai": "Hyundai Motor Company",
  "ibm": "International Business Machines Corporation",
  "icbc": "Industrial and Commercial Bank of China Limited",
  "ice": "IntercontinentalExchange, Inc.",
  "icu": "Shortdot SA",
  "id": "Perkumpulan Pengelola Nama Domain Internet Indonesia (PANDI)",
  "ie": "University College Dublin\nComputing Services\nComputer Centre",
  "ieee": "IEEE Global LLC",
  "ifm": "ifm electronic gmbh",
  "iinet": "Retired",
  "ikano": "Ikano S.A.",
  "il": "Internet Society of Israel",
  "im": "Isle of Man Government",
  "imamat": "Fondation Aga Khan (Aga Khan Foundation)",
  "imdb": "Amazon Registry Services, Inc.",
  "immo": "Binky Moon, LLC",
  "immobilien": "United TLD Holdco Ltd.",
  "in": "National Internet Exchange of India",
  "industries": "Binky Moon, LLC",
  "infiniti": "NISSAN MOTOR CO., LTD.",
  "info": "Afilias Limited",
  "ing": "Charleston Road Registry Inc.",
  "ink": "Top Level Design, LLC",
  "institute": "Binky Moon, LLC",
  "insurance": "fTLD Registry Services LLC",
  "insure": "Binky Moon, LLC",
  "int": "Internet Assigned Numbers Authority",
  "intel": "Intel Corporation",
  "international": "Binky Moon, LLC",
  "intuit": "Intuit Administrative Services, Inc.",
  "investments": "Binky Moon, LLC",
  "io": "IO Top Level Domain Registry\nCable and Wireless",
  "ipiranga": "Ipiranga Produtos de Petroleo S.A.",
  "iq": "Communications and Media Commission (CMC)",
  "ir": "Institute for Research in Fundamental Sciences",
  "irish": "Binky Moon, LLC",
  "is": "ISNIC - Internet Iceland ltd.",
  "iselect": "iSelect Ltd",
  "ismaili": "Fondation Aga Khan (Aga Khan Foundation)",
  "ist": "Istanbul Metropolitan Municipality",
  "istanbul": "Istanbul Metropolitan Municipality",
  "it": "IIT - CNR",
  "itau": "Itau Unibanco Holding S.A.",
  "itv": "ITV Services Limited",
  "iveco": "CNH Industrial N.V.",
  "iwc": "Richemont DNS Inc.",
  "jaguar": "Jaguar Land Rover Ltd",
  "java": "Oracle Corporation",
  "jcb": "JCB Co., Ltd.",
  "jcp": "JCP Media, Inc.",
  "je": "Island Networks (Jersey) Ltd.",
  "jeep": "FCA US LLC.",
  "jetzt": "Binky Moon, LLC",
  "jewelry": "Binky Moon, LLC",
  "jio": "Affinity Names, Inc.",
  "jlc": "Richemont DNS Inc.",
  "jll": "Jones Lang LaSalle Incorporated",
  "jm": "University of West Indies",
  "jmp": "Matrix IP LLC",
  "jnj": "Johnson & Johnson Services, Inc.",
  "jo": "National Information Technology Center (NITC)",
  "jobs": "Employ Media LLC",
  "joburg": "ZA Central Registry NPC trading as ZA Central Registry",
  "jot": "Amazon Registry Services, Inc.",
  "joy": "Amazon Registry Services, Inc.",
  "jp": "Japan Registry Services Co., Ltd.",
  "jpmorgan": "JPMorgan Chase Bank, National Association",
  "jprs": "Japan Registry Services Co., Ltd.",
  "juegos": "Uniregistry, Corp.",
  "juniper": "JUNIPER NETWORKS, INC.",
  "kaufen": "United TLD Holdco Ltd.",
  "kddi": "KDDI CORPORATION",
  "ke": "Kenya Network Information Center (KeNIC)",
  "kerryhotels": "Kerry Trading Co. Limited",
  "kerrylogistics": "Kerry Trading Co. Limited",
  "kerryproperties": "Kerry Trading Co. Limited",
  "kfh": "Kuwait Finance House",
  "kg": "AsiaInfo Telecommunication Enterprise",
  "kh": "Telecommunication Regulator of Cambodia (TRC)",
  "ki": "Ministry of Communications, Transport, and Tourism Development",
  "kia": "KIA MOTORS CORPORATION",
  "kim": "Afilias plc",
  "kinder": "Ferrero Trading Lux S.A.",
  "kindle": "Amazon Registry Services, Inc.",
  "kitchen": "Binky Moon, LLC",
  "kiwi": "DOT KIWI LIMITED",
  "km": "Comores Telecom",
  "kn": "Ministry of Finance, Sustainable Development Information & Technology",
  "koeln": "punkt.wien GmbH",
  "komatsu": "Komatsu Ltd.",
  "kosher": "Kosher Marketing Assets LLC",
  "kp": "Star Joint Venture Company",
  "kpmg": "KPMG International Cooperative (KPMG International Genossenschaft)",
  "kpn": "Koninklijke KPN N.V.",
  "kr": "Korea Internet & Security Agency (KISA)",
  "krd": "KRG Department of Information Technology",
  "kred": "KredTLD Pty Ltd",
  "kuokgroup": "Kerry Trading Co. Limited",
  "kw": "Communications and Information Technology Regulatory Authority",
  "ky": "Utility Regulation and Competition Office (OfReg)",
  "kyoto": "Academic Institution: Kyoto Jyoho Gakuen",
  "kz": "Association of IT Companies of Kazakhstan",
  "la": "Lao National Internet Committee (LANIC), Ministry of Posts and Telecommunications",
  "lacaixa": "CAIXA D'ESTALVIS I PENSIONS DE BARCELONA",
  "ladbrokes": "LADBROKES INTERNATIONAL PLC",
  "lamborghini": "Automobili Lamborghini S.p.A.",
  "lamer": "The Estée Lauder Companies Inc.",
  "lancaster": "LANCASTER",
  "lancia": "Fiat Chrysler Automobiles N.V.",
  "lancome": "L'Oréal",
  "land": "Binky Moon, LLC",
  "landrover": "Jaguar Land Rover Ltd",
  "lanxess": "LANXESS Corporation",
  "lasalle": "Jones Lang LaSalle Incorporated",
  "lat": "ECOM-LAC Federación de Latinoamérica y el Caribe para Internet y el Comercio Electrónico",
  "latino": "Dish DBS Corporation",
  "latrobe": "La Trobe University",
  "law": "Minds + Machines Group Limited",
  "lawyer": "United TLD Holdco, Ltd",
  "lb": "American University of Beirut\nComputing and Networking Services",
  "lc": "University of Puerto Rico",
  "lds": "IRI Domain Management, LLC",
  "lease": "Binky Moon, LLC",
  "leclerc": "A.C.D. LEC Association des Centres Distributeurs Edouard Leclerc",
  "lefrak": "LeFrak Organization, Inc.",
  "legal": "Binky Moon, LLC",
  "lego": "LEGO Juris A/S",
  "lexus": "TOYOTA MOTOR CORPORATION",
  "lgbt": "Afilias plc",
  "li": "SWITCH The Swiss Education & Research Network",
  "liaison": "Liaison Technologies, Incorporated",
  "lidl": "Schwarz Domains und Services GmbH & Co. KG",
  "life": "Binky Moon, LLC",
  "lifeinsurance": "American Council of Life Insurers",
  "lifestyle": "Lifestyle Domain Holdings, Inc.",
  "lighting": "Binky Moon, LLC",
  "like": "Amazon Registry Services, Inc.",
  "lilly": "Eli Lilly and Company",
  "limited": "Binky Moon, LLC",
  "limo": "Binky Moon, LLC",
  "lincoln": "Ford Motor Company",
  "linde": "Linde Aktiengesellschaft",
  "link": "Uniregistry, Corp.",
  "lipsy": "Lipsy Ltd",
  "live": "United TLD Holdco Ltd.",
  "living": "Lifestyle Domain Holdings, Inc.",
  "lixil": "LIXIL Group Corporation",
  "lk": "Council for Information Technology\nLK Domain Registrar",
  "llc": "Afilias plc",
  "loan": "dot Loan Limited",
  "loans": "Binky Moon, LLC",
  "locker": "Dish DBS Corporation",
  "locus": "Locus Analytics LLC",
  "loft": "Annco, Inc.",
  "lol": "Uniregistry, Corp.",
  "london": "Dot London Domains Limited",
  "lotte": "Lotte Holdings Co., Ltd.",
  "lotto": "Afilias plc",
  "love": "Merchant Law Group LLP",
  "lpl": "LPL Holdings, Inc.",
  "lplfinancial": "LPL Holdings, Inc.",
  "lr": "Data Technology Solutions, Inc.",
  "ls": "National University of Lesotho",
  "lt": "Kaunas University of Technology",
  "ltd": "Binky Moon, LLC",
  "ltda": "InterNetX Corp.",
  "lu": "RESTENA",
  "lundbeck": "H. Lundbeck A/S",
  "lupin": "LUPIN LIMITED",
  "luxe": "Top Level Domain Holdings Limited",
  "luxury": "Luxury Partners LLC",
  "lv": "University of Latvia\nInstitute of Mathematics and Computer Science\nDepartment of Network Solutions (DNS)",
  "ly": "General Post and Telecommunication Company",
  "ma": "Agence Nationale de Réglementation des Télécommunications (ANRT)",
  "macys": "Macys, Inc.",
  "madrid": "Comunidad de Madrid",
  "maif": "Mutuelle Assurance Instituteur France (MAIF)",
  "maison": "Binky Moon, LLC",
  "makeup": "L'Oréal",
  "man": "MAN SE",
  "management": "Binky Moon, LLC",
  "mango": "PUNTO FA S.L.",
  "map": "Charleston Road Registry Inc.",
  "market": "United TLD Holdco, Ltd",
  "marketing": "Binky Moon, LLC",
  "markets": "DOTMARKETS REGISTRY LTD",
  "marriott": "Marriott Worldwide Corporation",
  "marshalls": "The TJX Companies, Inc.",
  "maserati": "Fiat Chrysler Automobiles N.V.",
  "mattel": "Mattel Sites, Inc.",
  "mba": "Binky Moon, LLC",
  "mc": "Gouvernement de Monaco\nDirection des Communications Electroniques",
  "mcd": "Not assigned",
  "mcdonalds": "Not assigned",
  "mckinsey": "McKinsey Holdings, Inc.",
  "md": "MoldData S.E.",
  "me": "Government of Montenegro",
  "med": "Medistry LLC",
  "media": "Binky Moon, LLC",
  "meet": "Charleston Road Registry Inc.",
  "melbourne": "The Crown in right of the State of Victoria, represented by its Department of State Development, Business and Innovation",
  "meme": "Charleston Road Registry Inc.",
  "memorial": "Dog Beach, LLC",
  "men": "Exclusive Registry Limited",
  "menu": "Wedding TLD2, LLC",
  "meo": "Not assigned",
  "merckmsd": "MSD Registry Holdings, Inc.",
  "metlife": "MetLife Services and Solutions, LLC",
  "mf": "Not assigned",
  "mg": "NIC-MG (Network Information Center Madagascar)",
  "mh": "Office of the Cabinet",
  "miami": "Top Level Domain Holdings Limited",
  "microsoft": "Microsoft Corporation",
  "mil": "DoD Network Information Center",
  "mini": "Bayerische Motoren Werke Aktiengesellschaft",
  "mint": "Intuit Administrative Services, Inc.",
  "mit": "Massachusetts Institute of Technology",
  "mitsubishi": "Mitsubishi Corporation",
  "mk": "Macedonian Academic Research Network Skopje",
  "ml": "Agence des Technologies de l’Information et de la Communication",
  "mlb": "MLB Advanced Media DH, LLC",
  "mls": "The Canadian Real Estate Association",
  "mm": "Ministry of Communications, Posts & Telegraphs",
  "mma": "MMA IARD",
  "mn": "Datacom Co., Ltd.",
  "mo": "Macao Post and Telecommunications Bureau (CTT)",
  "mobi": "Afilias Technologies Limited dba dotMobi",
  "mobile": "Dish DBS Corporation",
  "mobily": "GreenTech Consultancy Company W.L.L.",
  "moda": "United TLD Holdco Ltd.",
  "moe": "Interlink Co., Ltd.",
  "moi": "Amazon Registry Services, Inc.",
  "mom": "Uniregistry, Corp.",
  "monash": "Monash University",
  "money": "Binky Moon, LLC",
  "monster": "Monster Worldwide, Inc.",
  "montblanc": "Not assigned",
  "mopar": "FCA US LLC.",
  "mormon": "IRI Domain Management, LLC (\"Applicant\")",
  "mortgage": "United TLD Holdco, Ltd",
  "moscow": "Foundation for Assistance for Internet Technologies and Infrastructure Development (FAITID)",
  "moto": "Motorola Trademark Holdings, LLC",
  "motorcycles": "DERMotorcycles, LLC",
  "mov": "Charleston Road Registry Inc.",
  "movie": "Binky Moon, LLC",
  "movistar": "Telefónica S.A.",
  "mp": "Saipan Datacom, Inc.",
  "mq": "MEDIASERV",
  "mr": "Université de Nouakchott Al Aasriya",
  "ms": "MNI Networks Ltd.",
  "msd": "MSD Registry Holdings, Inc.",
  "mt": "NIC (Malta)",
  "mtn": "MTN Dubai Limited",
  "mtpc": "Retired",
  "mtr": "MTR Corporation Limited",
  "mu": "Internet Direct Ltd",
  "museum": "Museum Domain Management Association",
  "mutual": "Northwestern Mutual MU TLD Registry, LLC",
  "mutuelle": "Retired",
  "mv": "Dhiraagu Pvt. Ltd. (DHIVEHINET)",
  "mw": "Malawi Sustainable Development Network Programme\n(Malawi SDNP)",
  "mx": "NIC-Mexico\nITESM - Campus Monterrey",
  "my": "MYNIC Berhad",
  "mz": "Centro de Informatica de Universidade Eduardo Mondlane",
  "na": "Namibian Network Information Center",
  "nab": "National Australia Bank Limited",
  "nadex": "Nadex Domains, Inc",
  "nagoya": "GMO Registry, Inc.",
  "name": "VeriSign Information Services, Inc.",
  "nationwide": "Nationwide Mutual Insurance Company",
  "natura": "NATURA COSMÉTICOS S.A.",
  "navy": "United TLD Holdco Ltd.",
  "nba": "NBA REGISTRY, LLC",
  "nc": "Office des Postes et Telecommunications",
  "ne": "SONITEL",
  "nec": "NEC Corporation",
  "net": "VeriSign Global Registry Services",
  "netbank": "COMMONWEALTH BANK OF AUSTRALIA",
  "netflix": "Netflix, Inc.",
  "network": "Binky Moon, LLC",
  "neustar": "NeuStar, Inc.",
  "new": "Charleston Road Registry Inc.",
  "newholland": "CNH Industrial N.V.",
  "news": "United TLD Holdco Ltd.",
  "next": "Next plc",
  "nextdirect": "Next plc",
  "nexus": "Charleston Road Registry Inc.",
  "nf": "Norfolk Island Data Services",
  "nfl": "NFL Reg Ops LLC",
  "ng": "Nigeria Internet Registration Association",
  "ngo": "Public Interest Registry",
  "nhk": "Japan Broadcasting Corporation (NHK)",
  "ni": "Universidad Nacional del Ingernieria\nCentro de Computo",
  "nico": "DWANGO Co., Ltd.",
  "nike": "NIKE, Inc.",
  "nikon": "NIKON CORPORATION",
  "ninja": "United TLD Holdco Ltd.",
  "nissan": "NISSAN MOTOR CO., LTD.",
  "nissay": "Nippon Life Insurance Company",
  "nl": "SIDN (Stichting Internet  Domeinregistratie Nederland)",
  "no": "UNINETT Norid A/S",
  "nokia": "Nokia Corporation",
  "northwesternmutual": "Northwestern Mutual Registry, LLC",
  "norton": "Symantec Corporation",
  "now": "Amazon Registry Services, Inc.",
  "nowruz": "Asia Green IT System Bilgisayar San. ve Tic. Ltd. Sti.",
  "nowtv": "Starbucks (HK) Limited",
  "np": "Mercantile Communications Pvt. Ltd.",
  "nr": "CENPAC NET",
  "nra": "NRA Holdings Company, INC.",
  "nrw": "Minds + Machines GmbH",
  "ntt": "NIPPON TELEGRAPH AND TELEPHONE CORPORATION",
  "nu": "The IUSN Foundation",
  "nyc": "The City of New York by and through the New York City Department of Information Technology & Telecommunications",
  "nz": "InternetNZ",
  "obi": "OBI Group Holding SE & Co. KGaA",
  "observer": "Top Level Spectrum, Inc.",
  "off": "Johnson Shareholdings, Inc.",
  "office": "Microsoft Corporation",
  "okinawa": "BRregistry, Inc.",
  "olayan": "Crescent Holding GmbH",
  "olayangroup": "Crescent Holding GmbH",
  "oldnavy": "The Gap, Inc.",
  "ollo": "Dish DBS Corporation",
  "om": "Telecommunications Regulatory Authority (TRA)",
  "omega": "The Swatch Group Ltd",
  "one": "One.com A/S",
  "ong": "Public Interest Registry",
  "onl": "I-REGISTRY Ltd., Niederlassung Deutschland",
  "online": "DotOnline Inc.",
  "onyourside": "Nationwide Mutual Insurance Company",
  "ooo": "INFIBEAM INCORPORATION LIMITED",
  "open": "American Express Travel Related Services Company, Inc.",
  "oracle": "Oracle Corporation",
  "orange": "Orange Brand Services Limited",
  "org": "Public Interest Registry (PIR)",
  "organic": "Afilias plc",
  "orientexpress": "Retired",
  "origins": "The Estée Lauder Companies Inc.",
  "osaka": "Osaka Registry Co., Ltd.",
  "otsuka": "Otsuka Holdings Co., Ltd.",
  "ott": "Dish DBS Corporation",
  "ovh": "OVH SAS",
  "pa": "Universidad Tecnologica de Panama",
  "page": "Charleston Road Registry Inc.",
  "pamperedchef": "Not assigned",
  "panasonic": "Panasonic Corporation",
  "panerai": "Richemont DNS Inc.",
  "paris": "City of Paris",
  "pars": "Asia Green IT System Bilgisayar San. ve Tic. Ltd. Sti.",
  "partners": "Binky Moon, LLC",
  "parts": "Binky Moon, LLC",
  "party": "Blue Sky Registry Limited",
  "passagens": "Travel Reservations SRL",
  "pay": "Amazon Registry Services, Inc.",
  "pccw": "PCCW Enterprises Limited",
  "pe": "Red Cientifica Peruana",
  "pet": "Afilias plc",
  "pf": "Gouvernement de la Polynésie française",
  "pfizer": "Pfizer Inc.",
  "pg": "PNG DNS Administration\nVice Chancellors Office\nThe Papua New Guinea University of Technology",
  "ph": "PH Domain Foundation",
  "pharmacy": "National Association of Boards of Pharmacy",
  "phd": "Charleston Road Registry Inc.",
  "philips": "Koninklijke Philips N.V.",
  "phone": "Dish DBS Corporation",
  "photo": "Uniregistry, Corp.",
  "photography": "Binky Moon, LLC",
  "photos": "Binky Moon, LLC",
  "physio": "PhysBiz Pty Ltd",
  "piaget": "Richemont DNS Inc.",
  "pics": "Uniregistry, Corp.",
  "pictet": "Pictet Europe S.A.",
  "pictures": "Binky Moon, LLC",
  "pid": "Top Level Spectrum, Inc.",
  "pin": "Amazon Registry Services, Inc.",
  "ping": "Ping Registry Provider, Inc.",
  "pink": "Afilias plc",
  "pioneer": "Pioneer Corporation",
  "pizza": "Binky Moon, LLC",
  "pk": "PKNIC",
  "pl": "Research and Academic Computer Network",
  "place": "Binky Moon, LLC",
  "play": "Charleston Road Registry Inc.",
  "playstation": "Sony Computer Entertainment Inc.",
  "plumbing": "Binky Moon, LLC",
  "plus": "Binky Moon, LLC",
  "pm": "Association Française pour le Nommage Internet en Coopération (A.F.N.I.C.)",
  "pn": "Pitcairn Island Administration",
  "pnc": "PNC Domain Co., LLC",
  "pohl": "Deutsche Vermögensberatung Aktiengesellschaft DVAG",
  "poker": "Afilias plc",
  "politie": "Politie Nederland",
  "porn": "ICM Registry PN LLC",
  "post": "Universal Postal Union",
  "pr": "Gauss Research Laboratory Inc.",
  "pramerica": "Prudential Financial, Inc.",
  "praxi": "Praxi S.p.A.",
  "press": "DotPress Inc.",
  "prime": "Amazon Registry Services, Inc.",
  "pro": "Registry Services Corporation\ndba RegistryPro",
  "prod": "Charleston Road Registry Inc.",
  "productions": "Binky Moon, LLC",
  "prof": "Charleston Road Registry Inc.",
  "progressive": "Progressive Casualty Insurance Company",
  "promo": "Afilias plc",
  "properties": "Binky Moon, LLC",
  "property": "Uniregistry, Corp.",
  "protection": "XYZ.COM LLC",
  "pru": "Prudential Financial, Inc.",
  "prudential": "Prudential Financial, Inc.",
  "ps": "Ministry Of Telecommunications &\nInformation Technology,\nGovernment Computer Center.",
  "pt": "Associação DNS.PT",
  "pub": "United TLD Holdco Ltd.",
  "pw": "Micronesia Investment and Development Corporation",
  "pwc": "PricewaterhouseCoopers LLP",
  "py": "NIC-PY",
  "qa": "Communications Regulatory Authority",
  "qpon": "dotCOOL, Inc.",
  "quebec": "PointQuébec Inc",
  "quest": "Quest ION Limited",
  "qvc": "QVC, Inc.",
  "racing": "Premier Registry Limited",
  "radio": "European Broadcasting Union (EBU)",
  "raid": "Johnson Shareholdings, Inc.",
  "re": "Association Française pour le Nommage Internet en Coopération (A.F.N.I.C.)",
  "read": "Amazon Registry Services, Inc.",
  "realestate": "dotRealEstate LLC",
  "realtor": "Real Estate Domains LLC",
  "realty": "Fegistry, LLC",
  "recipes": "Binky Moon, LLC",
  "red": "Afilias plc",
  "redstone": "Redstone Haute Couture Co., Ltd.",
  "redumbrella": "Travelers TLD, LLC",
  "rehab": "United TLD Holdco Ltd.",
  "reise": "Binky Moon, LLC",
  "reisen": "Binky Moon, LLC",
  "reit": "National Association of Real Estate Investment Trusts, Inc.",
  "reliance": "Reliance Industries Limited",
  "ren": "Beijing Qianxiang Wangjing Technology Development Co., Ltd.",
  "rent": "XYZ.COM LLC",
  "rentals": "Binky Moon, LLC",
  "repair": "Binky Moon, LLC",
  "report": "Binky Moon, LLC",
  "republican": "United TLD Holdco Ltd.",
  "rest": "Punto 2012 Sociedad Anonima Promotora de Inversion de Capital Variable",
  "restaurant": "Binky Moon, LLC",
  "review": "dot Review Limited",
  "reviews": "United TLD Holdco, Ltd.",
  "rexroth": "Robert Bosch GMBH",
  "rich": "I-REGISTRY Ltd., Niederlassung Deutschland",
  "richardli": "Pacific Century Asset Management (HK) Limited",
  "ricoh": "Ricoh Company, Ltd.",
  "rightathome": "Johnson Shareholdings, Inc.",
  "ril": "Reliance Industries Limited",
  "rio": "Empresa Municipal de Informática SA - IPLANRIO",
  "rip": "United TLD Holdco Ltd.",
  "rmit": "Royal Melbourne Institute of Technology",
  "ro": "National Institute for R&D in Informatics",
  "rocher": "Ferrero Trading Lux S.A.",
  "rocks": "United TLD Holdco, LTD.",
  "rodeo": "Top Level Domain Holdings Limited",
  "rogers": "Rogers Communications Canada Inc.",
  "room": "Amazon Registry Services, Inc.",
  "rs": "Serbian National Internet Domain Registry (RNIDS)",
  "rsvp": "Charleston Road Registry Inc.",
  "ru": "Coordination Center for TLD RU",
  "rugby": "World Rugby Strategic Developments Limited",
  "ruhr": "regiodot GmbH & Co. KG",
  "run": "Binky Moon, LLC",
  "rw": "Rwanda Information Communication and Technology Association (RICTA)",
  "rwe": "RWE AG",
  "ryukyu": "BRregistry, Inc.",
  "sa": "Communications and Information Technology Commission",
  "saarland": "dotSaarland GmbH",
  "safe": "Amazon Registry Services, Inc.",
  "safety": "Safety Registry Services, LLC.",
  "sakura": "SAKURA Internet Inc.",
  "sale": "United TLD Holdco, Ltd",
  "salon": "Binky Moon, LLC",
  "samsclub": "Wal-Mart Stores, Inc.",
  "samsung": "SAMSUNG SDS CO., LTD",
  "sandvik": "Sandvik AB",
  "sandvikcoromant": "Sandvik AB",
  "sanofi": "Sanofi",
  "sap": "SAP AG",
  "sapo": "Not assigned",
  "sarl": "Binky Moon, LLC",
  "sas": "Research IP LLC",
  "save": "Amazon Registry Services, Inc.",
  "saxo": "Saxo Bank A/S",
  "sb": "Solomon Telekom Company Limited",
  "sbi": "STATE BANK OF INDIA",
  "sbs": "SPECIAL BROADCASTING SERVICE CORPORATION",
  "sc": "VCS Pty Ltd",
  "sca": "SVENSKA CELLULOSA AKTIEBOLAGET SCA (publ)",
  "scb": "The Siam Commercial Bank Public Company Limited (\"SCB\")",
  "schaeffler": "Schaeffler Technologies AG & Co. KG",
  "schmidt": "SALM S.A.S.",
  "scholarships": "Scholarships.com, LLC",
  "school": "Binky Moon, LLC",
  "schule": "Binky Moon, LLC",
  "schwarz": "Schwarz Domains und Services GmbH & Co. KG",
  "science": "dot Science Limited",
  "scjohnson": "Johnson Shareholdings, Inc.",
  "scor": "SCOR SE",
  "scot": "Dot Scot Registry Limited",
  "sd": "Sudan Internet Society",
  "se": "The Internet Infrastructure Foundation",
  "search": "Charleston Road Registry Inc.",
  "seat": "SEAT, S.A. (Sociedad Unipersonal)",
  "secure": "Amazon Registry Services, Inc.",
  "security": "XYZ.COM LLC",
  "seek": "Seek Limited",
  "select": "iSelect Ltd",
  "sener": "Sener Ingeniería y Sistemas, S.A.",
  "services": "Binky Moon, LLC",
  "ses": "SES",
  "seven": "Seven West Media Ltd",
  "sew": "SEW-EURODRIVE GmbH & Co KG",
  "sex": "ICM Registry SX LLC",
  "sexy": "Uniregistry, Corp.",
  "sfr": "Societe Francaise du Radiotelephone - SFR",
  "sg": "Singapore Network Information Centre (SGNIC) Pte Ltd",
  "sh": "Government of St. Helena",
  "shangrila": "Shangri‐La International Hotel Management Limited",
  "sharp": "Sharp Corporation",
  "shaw": "Shaw Cablesystems G.P.",
  "shell": "Shell Information Technology International Inc",
  "shia": "Asia Green IT System Bilgisayar San. ve Tic. Ltd. Sti.",
  "shiksha": "Afilias plc",
  "shoes": "Binky Moon, LLC",
  "shop": "GMO Registry, Inc.",
  "shopping": "Binky Moon, LLC",
  "shouji": "QIHOO 360 TECHNOLOGY CO. LTD.",
  "show": "Binky Moon, LLC",
  "showtime": "CBS Domains Inc.",
  "shriram": "Shriram Capital Ltd.",
  "si": "Academic and Research Network of Slovenia (ARNES)",
  "silk": "Amazon Registry Services, Inc.",
  "sina": "Sina Corporation",
  "singles": "Binky Moon, LLC",
  "site": "DotSite Inc.",
  "sj": "UNINETT Norid A/S",
  "sk": "SK-NIC, a.s.",
  "ski": "STARTING DOT LIMITED",
  "skin": "L'Oréal",
  "sky": "Sky International AG",
  "skype": "Microsoft Corporation",
  "sl": "Sierratel",
  "sling": "Hughes Satellite Systems Corporation",
  "sm": "Telecom Italia San Marino S.p.A.",
  "smart": "Smart Communications, Inc. (SMART)",
  "smile": "Amazon Registry Services, Inc.",
  "sn": "Universite Cheikh Anta Diop\nNIC Senegal",
  "sncf": "SNCF (Société Nationale des Chemins de fer Francais)",
  "so": "Ministry of Post and Telecommunications",
  "soccer": "Binky Moon, LLC",
  "social": "United TLD Holdco Ltd.",
  "softbank": "SoftBank Group Corp.",
  "software": "United TLD Holdco, Ltd",
  "sohu": "Sohu.com Limited",
  "solar": "Binky Moon, LLC",
  "solutions": "Binky Moon, LLC",
  "song": "Amazon Registry Services, Inc.",
  "sony": "Sony Corporation",
  "soy": "Charleston Road Registry Inc.",
  "space": "DotSpace Inc.",
  "spiegel": "SPIEGEL-Verlag Rudolf Augstein GmbH & Co. KG",
  "sport": "Global Association of International Sports Federations (GAISF)",
  "spot": "Amazon Registry Services, Inc.",
  "spreadbetting": "DOTSPREADBETTING REGISTRY LTD",
  "sr": "Telesur",
  "srl": "InterNetX Corp.",
  "srt": "FCA US LLC.",
  "ss": "Not assigned",
  "st": "Tecnisys",
  "stada": "STADA Arzneimittel AG",
  "staples": "Staples, Inc.",
  "star": "Star India Private Limited",
  "starhub": "StarHub Limited",
  "statebank": "STATE BANK OF INDIA",
  "statefarm": "State Farm Mutual Automobile Insurance Company",
  "statoil": "Statoil ASA",
  "stc": "Saudi Telecom Company",
  "stcgroup": "Saudi Telecom Company",
  "stockholm": "Stockholms kommun",
  "storage": "XYZ.COM LLC",
  "store": "DotStore Inc.",
  "stream": "dot Stream Limited",
  "studio": "United TLD Holdco Ltd.",
  "study": "OPEN UNIVERSITIES AUSTRALIA PTY LTD",
  "style": "Binky Moon, LLC",
  "su": "Russian Institute for Development of Public Networks\n(ROSNIIROS)",
  "sucks": "Vox Populi Registry Ltd.",
  "supplies": "Binky Moon, LLC",
  "supply": "Binky Moon, LLC",
  "support": "Binky Moon, LLC",
  "surf": "Top Level Domain Holdings Limited",
  "surgery": "Binky Moon, LLC",
  "suzuki": "SUZUKI MOTOR CORPORATION",
  "sv": "SVNet",
  "swatch": "The Swatch Group Ltd",
  "swiftcover": "Swiftcover Insurance Services Limited",
  "swiss": "Swiss Confederation",
  "sx": "SX Registry SA B.V.",
  "sy": "National Agency for Network Services (NANS)",
  "sydney": "State of New South Wales, Department of Premier and Cabinet",
  "symantec": "Symantec Corporation",
  "systems": "Binky Moon, LLC",
  "sz": "University of Swaziland\nDepartment of Computer Science",
  "tab": "Tabcorp Holdings Limited",
  "taipei": "Taipei City Government",
  "talk": "Amazon Registry Services, Inc.",
  "taobao": "Alibaba Group Holding Limited",
  "target": "Target Domain Holdings, LLC",
  "tatamotors": "Tata Motors Ltd",
  "tatar": "Limited Liability Company \"Coordination Center of Regional Domain of Tatarstan Republic\"",
  "tattoo": "Uniregistry, Corp.",
  "tax": "Binky Moon, LLC",
  "taxi": "Binky Moon, LLC",
  "tc": "Melrex TC",
  "tci": "Asia Green IT System Bilgisayar San. ve Tic. Ltd. Sti.",
  "td": "l'Agence de Développement des Technologies de l'Information et de la Communication (ADETIC)",
  "tdk": "TDK Corporation",
  "team": "Binky Moon, LLC",
  "tech": "Dot Tech LLC",
  "technology": "Binky Moon, LLC",
  "tel": "Telnames Ltd.",
  "telecity": "TelecityGroup International Limited",
  "telefonica": "Telefónica S.A.",
  "temasek": "Temasek Holdings (Private) Limited",
  "tennis": "Binky Moon, LLC",
  "teva": "Teva Pharmaceutical Industries Limited",
  "tf": "Association Française pour le Nommage Internet en Coopération (A.F.N.I.C.)",
  "tg": "Autorite de Reglementation des secteurs de Postes et de Telecommunications (ART&P)",
  "th": "Thai Network Information Center Foundation",
  "thd": "Home Depot Product Authority, LLC",
  "theater": "Binky Moon, LLC",
  "theatre": "XYZ.COM LLC",
  "tiaa": "Teachers Insurance and Annuity Association of America",
  "tickets": "Accent Media Limited",
  "tienda": "Binky Moon, LLC",
  "tiffany": "Tiffany and Company",
  "tips": "Binky Moon, LLC",
  "tires": "Binky Moon, LLC",
  "tirol": "punkt Tirol GmbH",
  "tj": "Information Technology Center",
  "tjmaxx": "The TJX Companies, Inc.",
  "tjx": "The TJX Companies, Inc.",
  "tk": "Telecommunication Tokelau Corporation (Teletok)",
  "tkmaxx": "The TJX Companies, Inc.",
  "tl": "Autoridade Nacional de Comunicações",
  "tm": "TM Domain Registry Ltd",
  "tmall": "Alibaba Group Holding Limited",
  "tn": "Agence Tunisienne d'Internet",
  "to": "Government of the Kingdom of Tonga\nH.R.H. Crown Prince Tupouto'a\nc/o Consulate of Tonga",
  "today": "Binky Moon, LLC",
  "tokyo": "GMO Registry, Inc.",
  "tools": "Binky Moon, LLC",
  "top": "Jiangsu Bangning Science & Technology Co.,Ltd.",
  "toray": "Toray Industries, Inc.",
  "toshiba": "TOSHIBA Corporation",
  "total": "Total SA",
  "tours": "Binky Moon, LLC",
  "town": "Binky Moon, LLC",
  "toyota": "TOYOTA MOTOR CORPORATION",
  "toys": "Binky Moon, LLC",
  "tp": "Retired",
  "tr": "Middle East Technical University\nDepartment of Computer Engineering",
  "trade": "Elite Registry Limited",
  "trading": "DOTTRADING REGISTRY LTD",
  "training": "Binky Moon, LLC",
  "travel": "Dog\tBeach, LLC",
  "travelchannel": "Lifestyle Domain Holdings, Inc.",
  "travelers": "Travelers TLD, LLC",
  "travelersinsurance": "Travelers TLD, LLC",
  "trust": "Artemis Internet Inc",
  "trv": "Travelers TLD, LLC",
  "tt": "University of the West Indies\nFaculty of Engineering",
  "tube": "Latin American Telecom LLC",
  "tui": "TUI AG",
  "tunes": "Amazon Registry Services, Inc.",
  "tushu": "Amazon Registry Services, Inc.",
  "tv": "Ministry of Finance and Tourism",
  "tvs": "T V SUNDRAM IYENGAR  & SONS PRIVATE LIMITED",
  "tw": "Taiwan Network Information Center (TWNIC)",
  "tz": "Tanzania Network Information Centre (tzNIC)",
  "ua": "Hostmaster Ltd.",
  "ubank": "National Australia Bank Limited",
  "ubs": "UBS AG",
  "uconnect": "FCA US LLC.",
  "ug": "Uganda Online Ltd.",
  "uk": "Nominet UK",
  "um": "Not assigned",
  "unicom": "China United Network Communications Corporation Limited",
  "university": "Binky Moon, LLC",
  "uno": "Dot Latin LLC",
  "uol": "UBN INTERNET LTDA.",
  "ups": "UPS Market Driver, Inc.",
  "us": "NeuStar, Inc.",
  "uy": "SeCIU - Universidad de la Republica",
  "uz": "Computerization and Information Technologies Developing Center\nUZINFOCOM",
  "va": "Holy See - Vatican City State",
  "vacations": "Binky Moon, LLC",
  "vana": "Lifestyle Domain Holdings, Inc.",
  "vanguard": "The Vanguard Group, Inc.",
  "vc": "Ministry of Telecommunications, Science, Technology and Industry",
  "ve": "Comisión Nacional de Telecomunicaciones (CONATEL)",
  "vegas": "Dot Vegas, Inc.",
  "ventures": "Binky Moon, LLC",
  "verisign": "VeriSign, Inc.",
  "versicherung": "TLD-BOX Registrydienstleistungen GmbH",
  "vet": "United TLD Holdco, Ltd",
  "vg": "Telecommunications Regulatory Commission of the Virgin Islands",
  "vi": "Virgin Islands Public Telecommunications System, Inc.",
  "viajes": "Binky Moon, LLC",
  "video": "United TLD Holdco, Ltd",
  "vig": "VIENNA INSURANCE GROUP AG Wiener Versicherung Gruppe",
  "viking": "Viking River Cruises (Bermuda) Ltd.",
  "villas": "Binky Moon, LLC",
  "vin": "Binky Moon, LLC",
  "vip": "Minds + Machines Group Limited",
  "virgin": "Virgin Enterprises Limited",
  "visa": "Visa Worldwide Pte. Limited",
  "vision": "Binky Moon, LLC",
  "vista": "Vistaprint Limited",
  "vistaprint": "Vistaprint Limited",
  "viva": "Saudi Telecom Company",
  "vivo": "Telefonica Brasil S.A.",
  "vlaanderen": "DNS.be vzw",
  "vn": "Ministry of Information and Communications of Socialist Republic of Viet Nam",
  "vodka": "Top Level Domain Holdings Limited",
  "volkswagen": "Volkswagen Group of America Inc.",
  "volvo": "Volvo Holding Sverige Aktiebolag",
  "vote": "Monolith Registry LLC",
  "voting": "Valuetainment Corp.",
  "voto": "Monolith Registry LLC",
  "voyage": "Binky Moon, LLC",
  "vu": "Telecom Vanuatu Limited",
  "vuelos": "Travel Reservations SRL",
  "wales": "Nominet UK",
  "walmart": "Wal-Mart Stores, Inc.",
  "walter": "Sandvik AB",
  "wang": "Zodiac Wang Limited",
  "wanggou": "Amazon Registry Services, Inc.",
  "warman": "Weir Group IP Limited",
  "watch": "Binky Moon, LLC",
  "watches": "Richemont DNS Inc.",
  "weather": "International Business Machines Corporation",
  "weatherchannel": "International Business Machines Corporation",
  "webcam": "dot Webcam Limited",
  "weber": "Saint-Gobain Weber SA",
  "website": "DotWebsite Inc.",
  "wed": "Emergency Back-End Registry Operator Program - ICANN",
  "wedding": "Top Level Domain Holdings Limited",
  "weibo": "Sina Corporation",
  "weir": "Weir Group IP Limited",
  "wf": "Association Française pour le Nommage Internet en Coopération (A.F.N.I.C.)",
  "whoswho": "Who's Who Registry",
  "wien": "punkt.wien GmbH",
  "wiki": "Top Level Design, LLC",
  "williamhill": "William Hill Organization Limited",
  "win": "First Registry Limited",
  "windows": "Microsoft Corporation",
  "wine": "Binky Moon, LLC",
  "winners": "The TJX Companies, Inc.",
  "wme": "William Morris Endeavor Entertainment, LLC",
  "wolterskluwer": "Wolters Kluwer N.V.",
  "woodside": "Woodside Petroleum Limited",
  "work": "Top Level Domain Holdings Limited",
  "works": "Binky Moon, LLC",
  "world": "Binky Moon, LLC",
  "wow": "Amazon Registry Services, Inc.",
  "ws": "Government of Samoa Ministry of Foreign Affairs & Trade",
  "wtc": "World Trade Centers Association, Inc.",
  "wtf": "Binky Moon, LLC",
  "xbox": "Microsoft Corporation",
  "xerox": "Xerox DNHC LLC",
  "xfinity": "Comcast IP Holdings I, LLC",
  "xihuan": "QIHOO 360 TECHNOLOGY CO. LTD.",
  "xin": "Elegant Leader Limited",
  "测试": "Internet Assigned Numbers Authority",
  "कॉम": "VeriSign Sarl",
  "परीक्षा": "Internet Assigned Numbers Authority",
  "セール": "Amazon Registry Services, Inc.",
  "佛山": "Guangzhou YU Wei Information Technology Co., Ltd.",
  "ಭಾರತ": "National Internet eXchange of India",
  "慈善": "Excellent First Limited",
  "集团": "Eagle Horizon Limited",
  "在线": "TLD REGISTRY LIMITED",
  "한국": "KISA (Korea Internet & Security Agency)",
  "ଭାରତ": "National Internet eXchange of India",
  "大众汽车": "Volkswagen (China) Investment Co., Ltd.",
  "点看": "VeriSign Sarl",
  "คอม": "VeriSign Sarl",
  "ভাৰত": "National Internet eXchange of India",
  "ভারত": "National Internet Exchange of India",
  "八卦": "Zodiac Gemini Ltd",
  "‏موقع‎": "Suhub Electronic Establishment",
  "বাংলা": "Posts and Telecommunications Division",
  "公益": "China Organizational Name Administration Center",
  "公司": "Computer Network Information Center of Chinese Academy of Sciences （China Internet Network Information Center）",
  "香格里拉": "Shangri‐La International Hotel Management Limited",
  "网站": "Global Website TLD Asia Limited",
  "移动": "Afilias plc",
  "我爱你": "Tycoon Treasure Limited",
  "москва": "Foundation for Assistance for Internet Technologies and Infrastructure Development (FAITID)",
  "испытание": "Internet Assigned Numbers Authority",
  "қаз": "Association of IT Companies of Kazakhstan",
  "католик": "Pontificium Consilium de Comunicationibus Socialibus (PCCS) (Pontifical Council for Social Communication)",
  "онлайн": "CORE Association",
  "сайт": "CORE Association",
  "联通": "China United Network Communications Corporation Limited",
  "срб": "Serbian National Internet Domain Registry (RNIDS)",
  "бг": "Imena.BG AD",
  "бел": "Reliable Software, Ltd.",
  "‏קום‎": "VeriSign Sarl",
  "时尚": "RISE VICTORY LIMITED",
  "微博": "Sina Corporation",
  "테스트": "Internet Assigned Numbers Authority",
  "淡马锡": "Temasek Holdings (Private) Limited",
  "ファッション": "Amazon Registry Services, Inc.",
  "орг": "Public Interest Registry",
  "नेट": "VeriSign Sarl",
  "ストア": "Amazon Registry Services, Inc.",
  "삼성": "SAMSUNG SDS CO., LTD",
  "சிங்கப்பூர்": "Singapore Network Information Centre (SGNIC) Pte Ltd",
  "商标": "HU YI GLOBAL INFORMATION RESOURCES(HOLDING) COMPANY.HONGKONG LIMITED",
  "商店": "Binky Moon, LLC",
  "商城": "Zodiac Aquarius Limited",
  "дети": "The Foundation for Network Initiatives “The Smart Internet”",
  "мкд": "Macedonian Academic Research Network Skopje",
  "‏טעסט‎": "Internet Assigned Numbers Authority",
  "ею": "EURid vzw/asbl",
  "ポイント": "Amazon Registry Services, Inc.",
  "新闻": "Guangzhou YU Wei Information and Technology Co.,Ltd",
  "工行": "Industrial and Commercial Bank of China Limited",
  "家電": "Amazon Registry Services, Inc.",
  "‏كوم‎": "VeriSign Sarl",
  "中文网": "TLD REGISTRY LIMITED",
  "中信": "CITIC Group Corporation",
  "中国": "China Internet Network Information Center (CNNIC)",
  "中國": "China Internet Network Information Center (CNNIC)",
  "娱乐": "Binky Moon, LLC",
  "谷歌": "Charleston Road Registry Inc.",
  "భారత్": "National Internet Exchange of India",
  "ලංකා": "LK Domain Registry",
  "電訊盈科": "PCCW Enterprises Limited",
  "购物": "Minds + Machines Group Limited",
  "測試": "Internet Assigned Numbers Authority",
  "クラウド": "Amazon Registry Services, Inc.",
  "ભારત": "National Internet Exchange of India",
  "通販": "Amazon Registry Services, Inc.",
  "भारतम्": "National Internet eXchange of India",
  "भारत": "National Internet Exchange of India",
  "भारोत": "National Internet eXchange of India",
  "‏آزمایشی‎": "Internet Assigned Numbers Authority",
  "பரிட்சை": "Internet Assigned Numbers Authority",
  "网店": "Zodiac Taurus Ltd.",
  "संगठन": "Public Interest Registry",
  "餐厅": "HU YI GLOBAL INFORMATION RESOURCES (HOLDING) COMPANY. HONGKONG LIMITED",
  "网络": "Computer Network Information Center of Chinese Academy of Sciences （China Internet Network Information Center）",
  "ком": "VeriSign Sarl",
  "укр": "Ukrainian Network Information Centre (UANIC), Inc.",
  "香港": "Hong Kong Internet Registration Corporation Ltd.",
  "诺基亚": "Nokia Corporation",
  "食品": "Amazon Registry Services, Inc.",
  "δοκιμή": "Internet Assigned Numbers Authority",
  "飞利浦": "Koninklijke Philips N.V.",
  "‏إختبار‎": "Internet Assigned Numbers Authority",
  "台湾": "Taiwan Network Information Center (TWNIC)",
  "台灣": "Taiwan Network Information Center (TWNIC)",
  "手表": "Richemont DNS Inc.",
  "手机": "Beijing RITT-Net Technology Development Co., Ltd",
  "мон": "Datacom Co.,Ltd",
  "‏الجزائر‎": "CERIST",
  "‏عمان‎": "Telecommunications Regulatory Authority (TRA)",
  "‏ارامكو‎": "Aramco Services Company",
  "‏ایران‎": "Institute for Research in Fundamental Sciences (IPM)",
  "‏العليان‎": "Crescent Holding GmbH",
  "‏اتصالات‎": "Emirates Telecommunications Corporation (trading as Etisalat)",
  "‏امارات‎": "Telecommunications Regulatory Authority (TRA)",
  "‏بازار‎": "CORE Association",
  "‏موريتانيا‎": "Not assigned",
  "‏پاکستان‎": "National Telecommunication Corporation",
  "‏الاردن‎": "National Information Technology Center (NITC)",
  "‏موبايلي‎": "GreenTech Consultancy Company W.L.L.",
  "‏بارت‎": "National Internet eXchange of India",
  "‏بھارت‎": "National Internet Exchange of India",
  "‏المغرب‎": "Agence Nationale de Réglementation des Télécommunications (ANRT)",
  "‏ابوظبي‎": "Abu Dhabi Systems and Information Centre",
  "‏السعودية‎": "Communications and Information Technology Commission",
  "‏ڀارت‎": "National Internet eXchange of India",
  "‏كاثوليك‎": "Pontificium Consilium de Comunicationibus Socialibus (PCCS) (Pontifical Council for Social Communication)",
  "‏سودان‎": "Sudan Internet Society",
  "‏همراه‎": "Asia Green IT System Bilgisayar San. ve Tic. Ltd. Sti.",
  "‏عراق‎": "Communications and Media Commission (CMC)",
  "‏مليسيا‎": "MYNIC Berhad",
  "澳門": "Macao Post and Telecommunications Bureau (CTT)",
  "닷컴": "VeriSign Sarl",
  "政府": "Net-Chinese Co., Ltd.",
  "‏شبكة‎": "International Domain Registry Pty. Ltd.",
  "‏بيتك‎": "Kuwait Finance House",
  "‏عرب‎": "League of Arab States",
  "გე": "Information Technologies Development Center (ITDC)",
  "机构": "Public Interest Registry",
  "组织机构": "Public Interest Registry",
  "健康": "Stable Tone Limited",
  "ไทย": "Thai Network Information Center Foundation",
  "‏سورية‎": "National Agency for Network Services (NANS)",
  "招聘": "Dot Trademark TLD Holding Company Limited",
  "рус": "Rusnames Limited",
  "рф": "Coordination Center for TLD RU",
  "珠宝": "Richemont DNS Inc.",
  "‏تونس‎": "Agence Tunisienne d'Internet",
  "大拿": "VeriSign Sarl",
  "みんな": "Charleston Road Registry Inc.",
  "グーグル": "Charleston Road Registry Inc.",
  "ελ": "ICS-FORTH GR",
  "世界": "Stable Tone Limited",
  "書籍": "Amazon Registry Services, Inc.",
  "ഭാരതം": "National Internet eXchange of India",
  "ਭਾਰਤ": "National Internet Exchange of India",
  "网址": "KNET Co., Ltd",
  "닷넷": "VeriSign Sarl",
  "コム": "VeriSign Sarl",
  "天主教": "Pontificium Consilium de Comunicationibus Socialibus (PCCS) (Pontifical Council for Social Communication)",
  "游戏": "Binky Moon, LLC",
  "vermögensberater": "Deutsche Vermögensberatung Aktiengesellschaft DVAG",
  "vermögensberatung": "Deutsche Vermögensberatung Aktiengesellschaft DVAG",
  "企业": "Binky Moon, LLC",
  "信息": "Beijing Tele-info Network Technology Co., Ltd.",
  "嘉里大酒店": "Kerry Trading Co. Limited",
  "嘉里": "Kerry Trading Co. Limited",
  "‏مصر‎": "National Telecommunication Regulatory Authority - NTRA",
  "‏قطر‎": "Communications Regulatory Authority",
  "广东": "Guangzhou YU Wei Information Technology Co., Ltd.",
  "இலங்கை": "LK Domain Registry",
  "இந்தியா": "National Internet Exchange of India",
  "հայ": "\"Internet Society\" Non-governmental Organization",
  "新加坡": "Singapore Network Information Centre (SGNIC) Pte Ltd",
  "‏فلسطين‎": "Ministry of Telecom & Information Technology (MTIT)",
  "テスト": "Internet Assigned Numbers Authority",
  "政务": "China Organizational Name Administration Center",
  "xperia": "Sony Mobile Communications AB",
  "xxx": "ICM Registry LLC",
  "xyz": "XYZ.COM LLC",
  "yachts": "DERYachts, LLC",
  "yahoo": "Yahoo! Domain Services Inc.",
  "yamaxun": "Amazon Registry Services, Inc.",
  "yandex": "YANDEX, LLC",
  "ye": "TeleYemen",
  "yodobashi": "YODOBASHI CAMERA CO.,LTD.",
  "yoga": "Top Level Domain Holdings Limited",
  "yokohama": "GMO Registry, Inc.",
  "you": "Amazon Registry Services, Inc.",
  "youtube": "Charleston Road Registry Inc.",
  "yt": "Association Française pour le Nommage Internet en Coopération (A.F.N.I.C.)",
  "yun": "QIHOO 360 TECHNOLOGY CO. LTD.",
  "za": "ZA Domain Name Authority",
  "zappos": "Amazon Registry Services, Inc.",
  "zara": "Industria de Diseño Textil, S.A. (INDITEX, S.A.)",
  "zero": "Amazon Registry Services, Inc.",
  "zip": "Charleston Road Registry Inc.",
  "zippo": "Zadco Company",
  "zm": "Zambia Information and Communications Technology Authority (ZICTA)",
  "zone": "Binky Moon, LLC",
  "zuerich": "Kanton Zürich (Canton of Zurich)",
  "zw": "Postal and Telecommunications Regulatory Authority of Zimbabwe (POTRAZ)"
};